### ISSUE TITLE
1

### ISSUE THREAD

**Issue by qiaodashaoye** [MR-MaoJiu/tm#1]

**Comment by MR-MaoJiu** [comment]
谢谢，由于就我一个人然后经历有限就废弃掉了哈哈想法是可以的

**Comment by qiaodashaoye** [comment]
我也是开发，一起搞搞？




如果シ要銘記
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MR-MaoJiu/tm"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月3日(星期一) 晚上7:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MR-MaoJiu/tm] 想法不错，如何联系 (Issue #1)





 
谢谢，由于就我一个人然后经历有限就废弃掉了哈哈想法是可以的

**Comment by MR-MaoJiu** [comment]
可以啊我加你微信吧！我已经加你QQ了但是你没同意
